name = balustrade
title = Balustrade
description = Adds decorative stone, and wooden balustrades, posts, and railings.
author = TumeniNodes
supported_games = minetest_game
depends = default
optional_depends = granite

